### ISSUE TITLE
Adding support for shadow dom elements

### ISSUE THREAD

**Issue by zsigmas** [daattali/shinyscreenshot#26]
Hello Dean!

First of all thanks a lot for the great package. At the moment, I am trying to use it on a graph created with r2d3 that uses shadow dom. The old version of html2canvas does not support shadow dom, but since 1.4.1 it does support it.

Do you think it would be possible to upgrade it?

I have made a couple of informal testings locally, just replacing the library file, and all seems to be working ok with the new version.

Thanks a lot!

**Comment by daattali** [comment]
I actually purposely chose an older version than the latest one that was available at the time, because the latest one had some bugs. I don't recall the exact details right now, but I basically tried having many common shiny inputs and outputs on a page and tested to see which version had the best results overall. Have you done some more widespread testing with 1.4.1, or did you only test for your usecase?

**Comment by zsigmas** [comment]
Hi Dean,

No, in this case I have not tested extensively with a big variety of inputs. I just tested with r2d3 and I pinpointed the root of the problem to be the shadow dom.

In any case if you think upgrading may hinder the reliability of the package, I have found a solution that allows using shinyscreenshot with r2d3 without upgrading the html2canvas library. I have improved the title a bit so it refers to the shadow dom problem and is easier to find if someone else have the same problem.

When creating r2d3 charts one can opt-out of wrapping the charts inside a shadow dom by setting `options(r2d3.shadow = FALSE)` as described in https://rstudio.github.io/r2d3/reference/r2d3.html

This way r2d3 charts are correctly capture by shinyscreenshot.

From my side I find this solution satisfactory so I will close the issue :+1: 

Thanks for your support!

**Comment by daattali** [comment]
Glad you found a solution. It will be worthwhile to look into upgrading at some point. My package {timevis} was in a similar state - for a few years I could not upgrade the underlying javascript library because there were a few regressions bugs, and it took a few years until I was satisfied with the latest version that I finally upgraded. When I find time to do extensive testing, I'll try it out.
