### ISSUE TITLE
New function screenshotLink()

### ISSUE THREAD

**Issue by psimm** [daattali/shinyscreenshot#5]
Hi Dean, 

the package is very useful and easy to use, especially with your tutorial video! Thank you for creating it.

Would you please consider adding a `screenshotLink()` function that is like `screenshotButton()` but calls `actionLink()`? Like how there is a `downloadButton()` and a `downloadLink()` function in the shiny package.

**Comment by daattali** [comment]
Hi Paul, this can be achieved by using an actionLink and calling screenshot()  inside. 

I aded screenshotButton as a convenience/shortcut function because it seemed like a function that would be commonly used, but adding a very dollar similar link version in my opinion would not be commonly used. I make a conscious effort to only add functionality that I think will be useful for many people rather than adding lots of small esoteric features that increase the maintenance

**Comment by cnachtsheim** [comment]
Hi Dean,

Great package and video!    Thanks for doing it.  I noticed that the content of input fields doesn't seem to get captured.  For example, in your demo below, "test" in the textInput box does not show up in the capture.  Is that by design or am I missing something?  Chris

ui <- fluidPage(
  textInput("text", "Enter some text", "test"),
  actionButton("go", "Take a screenshot")
)

server <- function(input, output) {
  observeEvent(input$go, {
    screenshot()
  })
}

shinyApp(ui, server)

**Comment by daattali** [comment]
That seems to be a bug with the underlying javascript library `html2canvas`. Every screenshot library has limitations to it, I've tried many and this one seemed to be the best one. This is a known issue.
